### ISSUE TITLE
Model Size Problem

### ISSUE THREAD

**Issue by xieydd** [mightydeveloper/Deep-Compression-PyTorch#1]
Why after i use the three way, the model size is same of the three: @mightydeveloper 

```
-rw-r--r--. 1 root root 2.1M Oct 10 02:17 initial_model.ptmodel
-rw-r--r--. 1 root root 2.1M Oct 10 02:46 model_after_retraining.ptmodel
-rw-r--r--. 1 root root 2.1M Oct 10 03:04 model_after_weight_sharing.ptmodel
```

**Comment by mightydeveloper** [comment]
the `.ptmodel`s store every weight as a python object 
(so most of them will be NumPy array or something).
So even though they are sparse (have a lot of zeros), the model size will be exactly the same.
My implementation measures how much nonzeros are left after pruning, how much accuracy changes after weight sharing, and how much bytes are required after Huffman encoding. (For research purpose)
If you want to really compress the model for production use, you might need to modify the code and implement the encoding/decoding scheme.

**Comment by stepstep123** [comment]
> Why after i use the three way, the model size is same of the three: @mightydeveloper
> 
> ```
> -rw-r--r--. 1 root root 2.1M Oct 10 02:17 initial_model.ptmodel
> -rw-r--r--. 1 root root 2.1M Oct 10 02:46 model_after_retraining.ptmodel
> -rw-r--r--. 1 root root 2.1M Oct 10 03:04 model_after_weight_sharing.ptmodel
> ```

hello, thanks your issue.

have you soved the problem? i also want to save the pruned model with small size.

look farward to your reply.
best regards.
