### ISSUE TITLE
Why after huffman_encode, why the parameters increase?

### ISSUE THREAD

**Issue by xieydd** [mightydeveloper/Deep-Compression-PyTorch#2]
after prune the all parameter is 112422,when use huffman_encode,in change to 899388?? @mightydeveloper 

```
--- After Retraining ---
fc1.weight           | nonzeros =  107208 /  235200 ( 45.58%) | total_pruned =  127992 | shape = (300, 784)
fc1.bias             | nonzeros =     300 /     300 (100.00%) | total_pruned =       0 | shape = (300,)
fc2.weight           | nonzeros =    4338 /   30000 ( 14.46%) | total_pruned =   25662 | shape = (100, 300)
fc2.bias             | nonzeros =     100 /     100 (100.00%) | total_pruned =       0 | shape = (100,)
fc3.weight           | nonzeros =     466 /    1000 ( 46.60%) | total_pruned =     534 | shape = (10, 100)
fc3.bias             | nonzeros =      10 /      10 (100.00%) | total_pruned =       0 | shape = (10,)
alive: 112422, pruned : 154188, total: 266610, Compression rate :       2.37x  ( 57.83% pruned)

Layer           |   original compressed improvement percent
----------------------------------------------------------------------
fc1.weight      |     858868     176999       4.85x  20.61%
fc1.bias        |       1200       1200       1.00x 100.00%
fc2.weight      |      35108       7696       4.56x  21.92%
fc2.bias        |        400        400       1.00x 100.00%
fc3.weight      |       3772       1102       3.42x  29.22%
fc3.bias        |         40         40       1.00x 100.00%
----------------------------------------------------------------------
total           |     899388     187437       4.80x  20.84%
```

**Comment by mightydeveloper** [comment]
For the first part (where the all alive parameters equals to 112422), 
the nonzero numbers mean the **number of nonzero weight values**. 
for the second part (after Huffman encoding), 
the numbers mean the **number of Bytes** needed to store weights. 
Note that I didn't encode the biases so they use precisely 4 Bytes for each weight.
However, for normal weights (fc1.weight, fc2.weight, fc3.weight), 
I used either CSC or CSR matrix representation (https://en.wikipedia.org/wiki/Sparse_matrix).
So they use a bit fewer Bytes per each weight.
For example, for fc1 layer,  858868/235200 ~= 3.65. It uses approximately 3.65 bytes per weight
for fc2 layer, 35108/30000 ~= 1.17. It uses approximately 1.17 bytes per weight.
(Note that this efficiency comes from the sparsity of fc2 weights)

Maybe I'll add more information about the numbers in the future.
